import React, { useState, useEffect } from 'react';
import { 
  Copy, Check, Download, Code, Eye, FileText, Info, X, Maximize2, Minimize2
} from 'lucide-react';
import { downloadFile, ParsedMessage } from '../utils';
import MtriniIntroTrailer from './MtriniIntroTrailer';

interface ArtifactViewProps {
  artifact: ParsedMessage | null;
  onClose: () => void;
  themeColor: string;
  isExpanded?: boolean;
  onToggleExpand?: () => void;
}

export default function ArtifactView({ 
  artifact, 
  onClose, 
  themeColor, 
  isExpanded = false, 
  onToggleExpand 
}: ArtifactViewProps) {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'editor' | 'sandbox'>('editor');

  const title = artifact?.artifactTitle || 'script.txt';
  const isTrailer = title.toLowerCase().includes('trailer');

  useEffect(() => {
    if (isTrailer) {
      setActiveTab('sandbox');
    } else {
      setActiveTab('editor');
    }
  }, [artifact, isTrailer]);

  if (!artifact || !artifact.hasArtifact) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8 text-neutral-500 font-sans border-l border-[#E5DFD3] bg-[#FCFCFA]">
        <div className="text-center max-w-sm space-y-3.5 select-none">
          <div className="h-12 w-12 rounded-full border border-[#E2DFD3] bg-white flex items-center justify-center mx-auto shadow-sm">
            <Code className="w-5 h-5 text-neutral-500" />
          </div>
          <h3 className="text-xs font-mono font-bold uppercase tracking-wider text-neutral-700">Code Sandbox & Sandbox</h3>
          <p className="text-[11px] text-neutral-500 leading-relaxed">
            Massive scripts, Roblox Luau architectures, and HTML applications generated by Mtrini stream directly into this layout for streamlined reviews.
          </p>
        </div>
      </div>
    );
  }

  const code = artifact.artifactCode || '';
  const language = artifact.artifactLanguage || 'text';

  const getThemeWeights = (col: string) => {
    switch (col) {
      case 'emerald':
        return { text: 'text-emerald-700', bg: 'bg-emerald-50/80 border-emerald-100', textMuted: 'text-emerald-600' };
      case 'crimson':
        return { text: 'text-rose-700', bg: 'bg-rose-50/80 border-rose-100', textMuted: 'text-rose-600' };
      case 'amber':
        return { text: 'text-amber-700', bg: 'bg-amber-50/80 border-amber-100', textMuted: 'text-[#C2410C]' };
      case 'violet':
        return { text: 'text-violet-700', bg: 'bg-violet-50/80 border-violet-100', textMuted: 'text-violet-600' };
      case 'cyan':
      default:
        return { text: 'text-cyan-700', bg: 'bg-cyan-50/80 border-cyan-100', textMuted: 'text-cyan-600' };
    }
  };

  const weights = getThemeWeights(themeColor);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    downloadFile(title, code);
  };

  // Safe Sandboxing conditions
  const canPreview = ['html', 'htm', 'svg'].includes(language.toLowerCase()) || code.trim().startsWith('<') || isTrailer;

  return (
    <div className="flex-1 flex flex-col bg-white border-l border-[#E5DFD3] overflow-hidden font-sans relative">
      {/* Script Header Panel */}
      <div className="h-12 border-b border-[#E5DFD3] px-4 bg-[#F5F1EA] flex items-center justify-between select-none shrink-0">
        <div className="flex items-center gap-2">
          <FileText className={`w-4 h-4 ${weights.textMuted} shrink-0`} />
          <div className="flex flex-col">
            <span className="text-xs font-semibold text-neutral-800 truncate max-w-[200px] leading-tight">{title}</span>
            <span className="text-[9px] font-mono text-neutral-500 uppercase tracking-widest leading-none">workspace / {language}</span>
          </div>
        </div>

        {/* Tab Selection */}
        <div className="flex items-center gap-1.5 p-1 bg-white rounded-lg border border-[#E2DFD3]">
          <button
            onClick={() => setActiveTab('editor')}
            className={`px-3 py-1 text-[10px] font-semibold rounded-md transition-all cursor-pointer flex items-center gap-1 ${activeTab === 'editor' ? `${weights.bg} ${weights.text} border border-current shadow-3xs` : 'text-neutral-500 hover:text-neutral-850'}`}
          >
            <Code className="w-3 h-3" />
            Script Source
          </button>
          
          {canPreview && (
            <button
              onClick={() => setActiveTab('sandbox')}
              className={`px-3 py-1 text-[10px] font-semibold rounded-md transition-all cursor-pointer flex items-center gap-1 ${activeTab === 'sandbox' ? `${weights.bg} ${weights.text} font-bold border border-current shadow-3xs` : 'text-neutral-500 hover:text-neutral-850'}`}
            >
              <Eye className="w-3 h-3" />
              Interactive Preview
            </button>
          )}
        </div>

        {/* Quick Toolbar */}
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleCopy}
            className="p-1.5 hover:bg-white/80 border border-transparent hover:border-[#E2DFD3] rounded-lg text-neutral-600 hover:text-neutral-900 transition-all cursor-pointer relative group"
            title="Copy script"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
          </button>

          <button
            onClick={handleDownload}
            className="p-1.5 hover:bg-white/80 border border-transparent hover:border-[#E2DFD3] rounded-lg text-neutral-600 hover:text-neutral-900 transition-all cursor-pointer relative group"
            title="Download script"
          >
            <Download className="w-3.5 h-3.5" />
          </button>

          {onToggleExpand && (
            <button
              onClick={onToggleExpand}
              className="p-1.5 hover:bg-white/80 border border-transparent hover:border-[#E2DFD3] rounded-lg text-neutral-600 hover:text-neutral-900 transition-all cursor-pointer"
              title={isExpanded ? "Exit full screen" : "Toggle full screen (100% width)"}
            >
              {isExpanded ? <Minimize2 className="w-3.5 h-3.5 text-neutral-700" /> : <Maximize2 className="w-3.5 h-3.5 text-neutral-700" />}
            </button>
          )}

          <button
            onClick={onClose}
            className="p-1.5 hover:bg-red-50 text-neutral-400 hover:text-red-600 rounded-lg transition-colors cursor-pointer"
            title="Close view"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Editor Pane */}
      <div className="flex-1 overflow-auto bg-[#1E1E1C] flex flex-col h-full scrollbar-thin">
        {activeTab === 'editor' ? (
          <div className="relative flex flex-row font-mono text-[12px] leading-relaxed select-text h-full">
            {/* Roblox architecture warning */}
            {language.toLowerCase() === 'lua' && (
              <div className="absolute top-2 left-2 right-2 text-[10px] bg-amber-950/80 border border-amber-800/30 text-amber-250 p-2.5 rounded-lg flex items-start gap-2 backdrop-blur-md z-10 leading-relaxed font-sans">
                <Info className="w-4 h-4 text-amber-405 shrink-0 mt-0.5" />
                <div className="flex-1 text-amber-200">
                  <strong>Roblox Luau Optimizer Active:</strong> Event-driven triggers only. Banned raw loops to maintain robust garbage collection streams.
                </div>
              </div>
            )}

            {/* Line numbers column */}
            <div className="py-4 pl-3 pr-2 text-right text-neutral-600 bg-[#161614] border-r border-[#2d2d2a] shrink-0 select-none font-mono text-[11px]">
              {code.split('\n').map((_, i) => (
                <div key={i}>{i + 1}</div>
              ))}
            </div>

            {/* Code Body */}
            <pre className="py-4 px-4 overflow-x-auto text-neutral-200 flex-1 whitespace-pre custom-scrollbar">
              <code>{code}</code>
            </pre>
          </div>
        ) : (
          /* Sandbox Preview Pane */
          <div className="flex-1 h-full bg-[#FCFCFA] overflow-hidden relative flex flex-col">
            {isTrailer ? (
              <MtriniIntroTrailer />
            ) : (
              <>
                <div className="p-2 bg-[#F5F1EA] border-b border-[#E5DFD3] flex items-center justify-between text-[10px] font-sans select-none">
                  <span className="text-neutral-500">Virtual Sandbox Iframe compiled safely.</span>
                  <span className="text-emerald-750 bg-emerald-55 border border-emerald-250 px-1.5 py-0.5 rounded font-semibold uppercase animate-pulse">Running Interactive</span>
                </div>
                
                <iframe
                  srcDoc={code}
                  title="Mtrini runtime sandbox render"
                  sandbox="allow-scripts allow-modals"
                  className="w-full h-full flex-1 bg-white"
                />
              </>
            )}
          </div>
        )}
      </div>

      {/* Compiler logs status footer bar */}
      <div className="h-6 border-t border-[#E5DFD3] bg-[#FAF9F5] px-3 flex items-center justify-between text-[9px] font-mono text-neutral-500 shrink-0 select-none">
        <span>STATUS: ACTIVE • PARSED SUCCESS</span>
        <span>Mtrini sandbox link</span>
      </div>
    </div>
  );
}
