import React, { useState, useEffect, useRef } from 'react';
import { 
  Copy, Check, Download, Code, Eye, FileText, Info, X, Maximize2, Minimize2, Upload
} from 'lucide-react';
import { downloadFile, ParsedMessage } from '../utils';

interface ArtifactViewProps {
  artifact: ParsedMessage | null;
  onClose: () => void;
  themeColor: string;
  isExpanded?: boolean;
  onToggleExpand?: () => void;
  darkMode?: boolean;
}

export default function ArtifactView({ 
  artifact, 
  onClose, 
  themeColor, 
  isExpanded = false, 
  onToggleExpand,
  darkMode = true
}: ArtifactViewProps) {
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'editor' | 'sandbox'>('editor');
  const fileInputRef = useRef<HTMLInputElement>(null);

  const title = artifact?.artifactTitle || 'script.txt';

  useEffect(() => {
    setActiveTab('editor');
  }, [artifact]);

  if (!artifact || !artifact.hasArtifact) {
    return (
      <div className={`flex-1 flex flex-col items-center justify-center p-8 font-sans ${
        darkMode ? 'bg-[#0f0f12] text-neutral-400 border-neutral-900' : 'bg-neutral-50 text-neutral-600 border-neutral-200'
      }`}>
        <div className="text-center max-w-sm space-y-3.5 select-none">
          <div className={`h-12 w-12 rounded-full border flex items-center justify-center mx-auto shadow-sm ${
            darkMode ? 'bg-neutral-900 border-neutral-800 text-neutral-255' : 'bg-white border-neutral-300 text-neutral-750'
          }`}>
            <Code className="w-5 h-5" />
          </div>
          <h3 className={`text-xs font-mono font-bold uppercase tracking-wider ${
            darkMode ? 'text-neutral-300' : 'text-neutral-850'
          }`}>Code Sandbox & Review</h3>
          <p className="text-[11px] text-neutral-500 leading-relaxed">
            Complex scripts, advanced web applications, and interactive components generated by Mtrini stream directly into this layout for streamlined reviews.
          </p>
          <button
              onClick={() => fileInputRef.current?.click()}
              className={`mt-4 flex items-center justify-center gap-2 w-full p-3 border border-dashed text-xs font-bold transition-all cursor-pointer rounded-xl ${
                darkMode 
                  ? 'border-neutral-800 hover:border-neutral-700 bg-neutral-900 text-neutral-300 hover:bg-neutral-800' 
                  : 'border-neutral-300 hover:border-neutral-400 bg-white text-neutral-700 hover:bg-neutral-50 shadow-3xs'
              }`}
          >
            <Upload className="w-4 h-4" />
            Upload File for Analysis
          </button>
          <input type="file" ref={fileInputRef} className="hidden" onChange={(e) => {
            const file = e.target.files?.[0];
            if(file) {
                console.log(`Uploaded file for processing: ${file.name}`);
            }
          }} />
        </div>
      </div>
    );
  }

  const code = artifact.artifactCode || '';
  const language = artifact.artifactLanguage || 'text';

  const getThemeWeights = (col: string) => {
    switch (col) {
      case 'emerald':
        return { text: 'text-emerald-500', bg: 'bg-emerald-950/40 border-emerald-900/30', textMuted: 'text-emerald-500' };
      case 'crimson':
        return { text: 'text-rose-500', bg: 'bg-rose-950/40 border-rose-900/30', textMuted: 'text-rose-500' };
      case 'amber':
        return { text: 'text-amber-500', bg: 'bg-amber-950/40 border-amber-900/30', textMuted: 'text-amber-500' };
      case 'violet':
        return { text: 'text-violet-500', bg: 'bg-violet-950/40 border-violet-900/30', textMuted: 'text-violet-500' };
      case 'cyan':
      default:
        return { text: 'text-cyan-500', bg: 'bg-cyan-950/40 border-cyan-900/30', textMuted: 'text-cyan-500' };
    }
  };

  const weights = getThemeWeights(themeColor);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    downloadFile(title, code);
  };

  const canPreview = ['html', 'htm', 'svg', 'xml'].includes(language.toLowerCase()) || code.trim().startsWith('<');

  return (
    <div className={`flex-1 flex flex-col overflow-hidden font-sans relative h-full w-full transition-all duration-200 ${
      darkMode ? 'bg-neutral-900 text-neutral-200' : 'bg-white text-neutral-800'
    }`}>
      {/* Script Header Panel */}
      <div className={`h-14 px-4 flex items-center justify-between select-none shrink-0 border-b transition-all duration-200 ${
        darkMode ? 'border-neutral-950 bg-neutral-950' : 'border-neutral-250 bg-neutral-100'
      }`}>
        <div className="flex items-center gap-2.5">
          <FileText className={`w-4 h-4 ${weights.textMuted} shrink-0`} />
          <div className="flex flex-col">
            <span className={`text-xs font-bold truncate max-w-[200px] leading-tight ${
              darkMode ? 'text-white' : 'text-neutral-900'
            }`}>{title}</span>
            <span className="text-[9px] font-mono text-neutral-500 uppercase tracking-widest leading-none">workspace / {language}</span>
          </div>
        </div>

        {/* Tab Selection */}
        <div className={`flex items-center gap-1.5 p-1 rounded-lg border transition-all duration-200 ${
          darkMode ? 'bg-neutral-900 border-neutral-800' : 'bg-neutral-200/60 border-neutral-300'
        }`}>
          <button
            onClick={() => setActiveTab('editor')}
            className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all cursor-pointer flex items-center gap-1.5 ${
              activeTab === 'editor' 
                ? (darkMode 
                    ? 'bg-neutral-850 text-white border border-neutral-750 shadow-3xs' 
                    : 'bg-white text-neutral-900 border border-neutral-300 shadow-3xs'
                  ) 
                : 'text-neutral-500 hover:text-neutral-800 dark:hover:text-white'
            }`}
          >
            <Code className="w-3.5 h-3.5" />
            Script Source
          </button>
          
          {canPreview && (
            <button
              onClick={() => setActiveTab('sandbox')}
              className={`px-3 py-1 text-[10px] font-bold rounded-md transition-all cursor-pointer flex items-center gap-1.5 ${
                activeTab === 'sandbox' 
                  ? (darkMode 
                      ? 'bg-neutral-850 text-white border border-neutral-750 shadow-3xs' 
                      : 'bg-white text-neutral-900 border border-neutral-300 shadow-3xs'
                    ) 
                  : 'text-neutral-500 hover:text-neutral-800 dark:hover:text-white'
              }`}
            >
              <Eye className="w-3.5 h-3.5" />
              Preview Output
            </button>
          )}
        </div>

        {/* Quick Toolbar */}
        <div className="flex items-center gap-1.5">
          <button
            onClick={handleCopy}
            className={`p-1.5 border border-transparent rounded-lg transition-all cursor-pointer ${
              darkMode ? 'hover:bg-neutral-800 hover:border-neutral-800 text-neutral-400 hover:text-white' : 'hover:bg-neutral-200 hover:border-neutral-250 text-neutral-550 hover:text-neutral-900'
            }`}
            title="Copy script"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
          </button>

          <button
            onClick={handleDownload}
            className={`p-1.5 border border-transparent rounded-lg transition-all cursor-pointer ${
              darkMode ? 'hover:bg-neutral-800 hover:border-neutral-800 text-neutral-400 hover:text-white' : 'hover:bg-neutral-200 hover:border-neutral-250 text-neutral-550 hover:text-neutral-900'
            }`}
            title="Download script"
          >
            <Download className="w-3.5 h-3.5" />
          </button>

          {onToggleExpand && (
            <button
              onClick={onToggleExpand}
              className={`p-1.5 border border-transparent rounded-lg transition-all cursor-pointer ${
                darkMode ? 'hover:bg-neutral-800 hover:border-neutral-800 text-neutral-400 hover:text-white' : 'hover:bg-neutral-200 hover:border-neutral-250 text-neutral-550 hover:text-neutral-900'
              }`}
              title={isExpanded ? "Exit full screen" : "Toggle full screen (100% width)"}
            >
              {isExpanded ? <Minimize2 className="w-3.5 h-3.5" /> : <Maximize2 className="w-3.5 h-3.5" />}
            </button>
          )}

          <button
            onClick={onClose}
            className={`p-1.5 rounded-lg transition-all cursor-pointer ${
              darkMode ? 'hover:bg-rose-950/40 text-neutral-500 hover:text-rose-400' : 'hover:bg-rose-50 text-neutral-500 hover:text-rose-600'
            }`}
            title="Close view"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Editor or Preview Pane */}
      <div className="flex-1 overflow-auto flex flex-col h-full scrollbar-thin">
        {activeTab === 'editor' ? (
          <div className={`relative flex flex-row font-mono text-[12px] leading-relaxed select-text h-full flex-1 ${
            darkMode ? 'bg-[#0a0a0c]' : 'bg-[#fcfcf9]'
          }`}>
            {/* Roblox architecture warning */}
            {language.toLowerCase() === 'lua' && (
              <div className="absolute top-2 left-2 right-2 text-[10px] bg-amber-950/80 border border-amber-900/30 text-amber-200 p-2.5 rounded-lg flex items-start gap-2 backdrop-blur-md z-10 leading-relaxed font-sans">
                <Info className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
                <div className="flex-1 text-amber-200">
                  <strong>Roblox Luau Optimizer Active:</strong> Event-driven triggers only. Banned raw loops to maintain robust garbage collection streams.
                </div>
              </div>
            )}

            {/* Line numbers column */}
            <div className={`py-4 pl-3 pr-2 text-right shrink-0 select-none font-mono text-[11px] border-r transition-all duration-200 ${
              darkMode ? 'bg-[#09090b] text-neutral-600 border-neutral-950' : 'bg-neutral-105 text-neutral-400 border-neutral-200'
            }`}>
              {code.split('\n').map((_, i) => (
                <div key={i}>{i + 1}</div>
              ))}
            </div>

            {/* Code Body */}
            <pre className={`py-4 px-4 overflow-x-auto flex-1 whitespace-pre custom-scrollbar font-mono text-[12.5px] ${
              darkMode ? 'text-neutral-250' : 'text-neutral-850'
            }`}>
              <code>{code}</code>
            </pre>
          </div>
        ) : (
          /* Sandbox Preview Pane - STRICTLY DEEP BLACK with high contrast elements */
          <div className="flex-1 h-full bg-black overflow-hidden relative flex flex-col">
            <div className="p-2 bg-neutral-950 border-b border-neutral-905 flex items-center justify-between text-[10px] font-sans select-none">
              <span className="text-neutral-500">Virtual Sandbox rendering on secure sandbox iframe container.</span>
              <span className="text-emerald-400 bg-emerald-950/40 border border-emerald-900/30 px-1.5 py-0.5 rounded font-bold uppercase tracking-wider animate-pulse flex items-center gap-1">
                <span className="h-1.5 w-1.5 bg-emerald-400 rounded-full inline-block" />
                <span>Running Stage</span>
              </span>
            </div>
            
            <iframe
              srcDoc={code}
              title="Mtrini runtime sandbox render"
              sandbox="allow-scripts allow-modals"
              className="w-full h-full flex-1 bg-black border-none"
            />
          </div>
        )}
      </div>

      {/* Compiler logs status footer bar */}
      <div className={`h-6 px-3 flex items-center justify-between text-[9px] font-mono shrink-0 select-none transition-all duration-200 border-t ${
        darkMode ? 'border-neutral-950 bg-neutral-950 text-neutral-500' : 'border-neutral-200 bg-neutral-100 text-neutral-650'
      }`}>
        <span>STATUS: SECURE WORKSPACE • INTERACTIVE CHANNEL PROVISIONED</span>
        <span>Mtrini sandbox link</span>
      </div>
    </div>
  );
}
